import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton
} from '@clerk/nextjs'

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {PitchProvider} from "@/contexts/PitchContext";
import {SideBar} from "@/app/_components/nav/side-bar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={inter.className}>

            <PitchProvider>
                {children}
            </PitchProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}
